BEGIN;

CREATE SCHEMA IF NOT EXISTS pdb_office;

CREATE TABLE IF NOT EXISTS pdb_office.documents (
  document_key TEXT PRIMARY KEY,
  payload JSONB NOT NULL,
  revision BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMIT;
